/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Go2Asia Content API
 * API для работы с контентом (Atlas, Pulse, Blog)
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  CitiesResponse,
  City,
  CountriesResponse,
  Country,
  GetCitiesParams,
  GetCountriesParams,
  GetPlacesParams,
  InternalServerErrorResponse,
  NotFoundResponse,
  Place,
  PlacesResponse
} from '../content.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает список всех стран с пагинацией
 * @summary Получить список стран
 */
export const getCountries = (
    params?: GetCountriesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CountriesResponse>(
      {url: `/countries`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCountriesQueryKey = (params?: GetCountriesParams,) => {
    return [
    `/countries`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCountriesQueryOptions = <TData = Awaited<ReturnType<typeof getCountries>>, TError = BadRequestResponse | InternalServerErrorResponse>(params?: GetCountriesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountriesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountries>>> = ({ signal }) => getCountries(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountriesQueryResult = NonNullable<Awaited<ReturnType<typeof getCountries>>>
export type GetCountriesQueryError = BadRequestResponse | InternalServerErrorResponse


/**
 * @summary Получить список стран
 */

export function useGetCountries<TData = Awaited<ReturnType<typeof getCountries>>, TError = BadRequestResponse | InternalServerErrorResponse>(
 params?: GetCountriesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCountriesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает детальную информацию о стране
 * @summary Получить страну по ID
 */
export const getCountryById = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Country>(
      {url: `/countries/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCountryByIdQueryKey = (id?: string,) => {
    return [
    `/countries/${id}`
    ] as const;
    }

    
export const getGetCountryByIdQueryOptions = <TData = Awaited<ReturnType<typeof getCountryById>>, TError = NotFoundResponse | InternalServerErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountryById>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountryByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountryById>>> = ({ signal }) => getCountryById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountryById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountryByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCountryById>>>
export type GetCountryByIdQueryError = NotFoundResponse | InternalServerErrorResponse


/**
 * @summary Получить страну по ID
 */

export function useGetCountryById<TData = Awaited<ReturnType<typeof getCountryById>>, TError = NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountryById>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCountryByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает список городов с фильтрацией по стране
 * @summary Получить список городов
 */
export const getCities = (
    params?: GetCitiesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CitiesResponse>(
      {url: `/cities`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCitiesQueryKey = (params?: GetCitiesParams,) => {
    return [
    `/cities`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCitiesQueryOptions = <TData = Awaited<ReturnType<typeof getCities>>, TError = BadRequestResponse | InternalServerErrorResponse>(params?: GetCitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCities>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCitiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCities>>> = ({ signal }) => getCities(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCities>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getCities>>>
export type GetCitiesQueryError = BadRequestResponse | InternalServerErrorResponse


/**
 * @summary Получить список городов
 */

export function useGetCities<TData = Awaited<ReturnType<typeof getCities>>, TError = BadRequestResponse | InternalServerErrorResponse>(
 params?: GetCitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCities>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCitiesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получить город по ID
 */
export const getCityById = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<City>(
      {url: `/cities/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCityByIdQueryKey = (id?: string,) => {
    return [
    `/cities/${id}`
    ] as const;
    }

    
export const getGetCityByIdQueryOptions = <TData = Awaited<ReturnType<typeof getCityById>>, TError = NotFoundResponse | InternalServerErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCityById>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCityByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCityById>>> = ({ signal }) => getCityById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCityById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCityByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCityById>>>
export type GetCityByIdQueryError = NotFoundResponse | InternalServerErrorResponse


/**
 * @summary Получить город по ID
 */

export function useGetCityById<TData = Awaited<ReturnType<typeof getCityById>>, TError = NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCityById>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCityByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает список мест с фильтрацией
 * @summary Получить список мест
 */
export const getPlaces = (
    params?: GetPlacesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PlacesResponse>(
      {url: `/places`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetPlacesQueryKey = (params?: GetPlacesParams,) => {
    return [
    `/places`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetPlacesQueryOptions = <TData = Awaited<ReturnType<typeof getPlaces>>, TError = BadRequestResponse | InternalServerErrorResponse>(params?: GetPlacesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlaces>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlacesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlaces>>> = ({ signal }) => getPlaces(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlaces>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPlacesQueryResult = NonNullable<Awaited<ReturnType<typeof getPlaces>>>
export type GetPlacesQueryError = BadRequestResponse | InternalServerErrorResponse


/**
 * @summary Получить список мест
 */

export function useGetPlaces<TData = Awaited<ReturnType<typeof getPlaces>>, TError = BadRequestResponse | InternalServerErrorResponse>(
 params?: GetPlacesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlaces>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPlacesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получить место по ID
 */
export const getPlaceById = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Place>(
      {url: `/places/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPlaceByIdQueryKey = (id?: string,) => {
    return [
    `/places/${id}`
    ] as const;
    }

    
export const getGetPlaceByIdQueryOptions = <TData = Awaited<ReturnType<typeof getPlaceById>>, TError = NotFoundResponse | InternalServerErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlaceById>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlaceByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlaceById>>> = ({ signal }) => getPlaceById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlaceById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPlaceByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPlaceById>>>
export type GetPlaceByIdQueryError = NotFoundResponse | InternalServerErrorResponse


/**
 * @summary Получить место по ID
 */

export function useGetPlaceById<TData = Awaited<ReturnType<typeof getPlaceById>>, TError = NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlaceById>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPlaceByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




