/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Go2Asia Auth API
 * API для работы с авторизацией и профилями пользователей
 * OpenAPI spec version: 1.0.0
 */
export type UserProfileRole = typeof UserProfileRole[keyof typeof UserProfileRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserProfileRole = {
  spacer: 'spacer',
  vip: 'vip',
  pro: 'pro',
} as const;

export interface UserProfile {
  id: string;
  email: string;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  avatar?: string | null;
  role?: UserProfileRole;
  createdAt: string;
  updatedAt?: string;
}

export interface UpdateProfileRequest {
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  avatar?: string | null;
}

export type ClerkWebhookEventType = typeof ClerkWebhookEventType[keyof typeof ClerkWebhookEventType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClerkWebhookEventType = {
  usercreated: 'user.created',
  userupdated: 'user.updated',
  userdeleted: 'user.deleted',
} as const;

export type ClerkWebhookEventDataEmailAddressesItem = {
  email_address?: string;
};

export type ClerkWebhookEventData = {
  id?: string;
  email_addresses?: ClerkWebhookEventDataEmailAddressesItem[];
  /** @nullable */
  first_name?: string | null;
  /** @nullable */
  last_name?: string | null;
  /** @nullable */
  image_url?: string | null;
};

export interface ClerkWebhookEvent {
  type: ClerkWebhookEventType;
  data: ClerkWebhookEventData;
}

export type ErrorResponseError = {
  code: string;
  message: string;
  /** @nullable */
  traceId?: string | null;
};

export interface ErrorResponse {
  error: ErrorResponseError;
}

/**
 * Неверный запрос
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Требуется авторизация
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Доступ запрещён
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Ресурс не найден
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Конфликт
 */
export type ConflictResponse = ErrorResponse;

/**
 * Превышен лимит запросов
 */
export type TooManyRequestsResponse = ErrorResponse;

/**
 * Внутренняя ошибка сервера
 */
export type InternalServerErrorResponse = ErrorResponse;

/**
 * Количество элементов на странице
 */
export type LimitParameter = number;

/**
 * Курсор для пагинации
 */
export type CursorParameter = string;

export type ClerkWebhook200 = {
  success?: boolean;
};

