/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Go2Asia Content API
 * API для работы с контентом (Atlas, Pulse, Blog)
 * OpenAPI spec version: 1.0.0
 */
export interface Country {
  id: string;
  name: string;
  /**
   * @minLength 2
   * @maxLength 3
   */
  code: string;
  /** @nullable */
  flag?: string | null;
  /** @nullable */
  description?: string | null;
  citiesCount?: number;
  placesCount?: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface CountriesResponse {
  items: Country[];
  /** @nullable */
  nextCursor?: string | null;
  hasMore: boolean;
}

export interface City {
  id: string;
  name: string;
  countryId: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  placesCount?: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface CitiesResponse {
  items: City[];
  /** @nullable */
  nextCursor?: string | null;
  hasMore: boolean;
}

export interface Place {
  id: string;
  name: string;
  cityId: string;
  /** @nullable */
  description?: string | null;
  latitude?: number;
  longitude?: number;
  type?: string;
  categories?: string[];
  photos?: string[];
  createdAt?: string;
  updatedAt?: string;
}

export interface PlacesResponse {
  items: Place[];
  /** @nullable */
  nextCursor?: string | null;
  hasMore: boolean;
}

export interface Event {
  id: string;
  title: string;
  /** @nullable */
  description?: string | null;
  startTime: string;
  /** @nullable */
  endTime?: string | null;
  cityId?: string;
  /** @nullable */
  placeId?: string | null;
  type?: string;
  category?: string;
  /** @nullable */
  organizerId?: string | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface EventsResponse {
  items: Event[];
  /** @nullable */
  nextCursor?: string | null;
  hasMore: boolean;
}

export interface Article {
  id: string;
  slug: string;
  title: string;
  /** @nullable */
  excerpt?: string | null;
  content?: string;
  authorId?: string;
  /** @nullable */
  category?: string | null;
  tags?: string[];
  /** @nullable */
  coverImage?: string | null;
  publishedAt: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface ArticlesResponse {
  items: Article[];
  /** @nullable */
  nextCursor?: string | null;
  hasMore: boolean;
}

export type ErrorResponseError = {
  code: string;
  message: string;
  /** @nullable */
  key?: string | null;
  /** @nullable */
  traceId?: string | null;
};

export interface ErrorResponse {
  error: ErrorResponseError;
}

/**
 * Неверный запрос
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Требуется авторизация
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Доступ запрещён
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Ресурс не найден
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Конфликт
 */
export type ConflictResponse = ErrorResponse;

/**
 * Превышен лимит запросов
 */
export type TooManyRequestsResponse = ErrorResponse;

/**
 * Внутренняя ошибка сервера
 */
export type InternalServerErrorResponse = ErrorResponse;

/**
 * Количество элементов на странице
 */
export type LimitParameter = number;

/**
 * Курсор для пагинации (cursor-based)
 */
export type CursorParameter = string;

export type GetCountriesParams = {
/**
 * Количество элементов на странице
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
/**
 * Курсор для пагинации (cursor-based)
 */
cursor?: CursorParameter;
};

export type GetCitiesParams = {
/**
 * Фильтр по стране
 */
countryId?: string;
/**
 * Количество элементов на странице
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
/**
 * Курсор для пагинации (cursor-based)
 */
cursor?: CursorParameter;
};

export type GetPlacesParams = {
cityId?: string;
types?: string[];
/**
 * Количество элементов на странице
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
/**
 * Курсор для пагинации (cursor-based)
 */
cursor?: CursorParameter;
};

export type GetEventsParams = {
cityId?: string;
date?: GetEventsDate;
/**
 * Количество элементов на странице
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
/**
 * Курсор для пагинации (cursor-based)
 */
cursor?: CursorParameter;
};

export type GetEventsDate = typeof GetEventsDate[keyof typeof GetEventsDate];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetEventsDate = {
  today: 'today',
  tomorrow: 'tomorrow',
  week: 'week',
} as const;

export type GetArticlesParams = {
category?: string;
/**
 * Количество элементов на странице
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
/**
 * Курсор для пагинации (cursor-based)
 */
cursor?: CursorParameter;
};

