/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Go2Asia Referral API
 * API для работы с реферальной программой
 * OpenAPI spec version: 1.0.0
 */
export interface ReferralStats {
  /** @minimum 0 */
  totalReferrals: number;
  /** @minimum 0 */
  activeReferrals: number;
  /** @minimum 0 */
  totalSubReferrals?: number;
  /** @minimum 0 */
  totalEarned: number;
  referralCode?: string;
}

export interface ReferralNode {
  userId: string;
  email?: string;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  registeredAt: string;
  isActive?: boolean;
  subReferrals?: ReferralNode[];
}

export interface ReferralTree {
  sponsorId: string;
  referrals: ReferralNode[];
}

export interface RegisterReferralRequest {
  referralCode: string;
  /** ID нового пользователя */
  userId: string;
}

export interface RegisterReferralResponse {
  success: boolean;
  sponsorId: string;
  message?: string;
}

export type ErrorResponseError = {
  code: string;
  message: string;
  /** @nullable */
  traceId?: string | null;
};

export interface ErrorResponse {
  error: ErrorResponseError;
}

/**
 * Неверный запрос
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Требуется авторизация
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Доступ запрещён
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Ресурс не найден
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Конфликт
 */
export type ConflictResponse = ErrorResponse;

/**
 * Превышен лимит запросов
 */
export type TooManyRequestsResponse = ErrorResponse;

/**
 * Внутренняя ошибка сервера
 */
export type InternalServerErrorResponse = ErrorResponse;

/**
 * Количество элементов на странице
 */
export type LimitParameter = number;

/**
 * Курсор для пагинации
 */
export type CursorParameter = string;

export type GetReferralTreeParams = {
/**
 * Глубина дерева (1 = только прямые рефералы)
 * @minimum 1
 * @maximum 5
 */
depth?: number;
};

