/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Go2Asia Token API
 * API для работы с токенами, балансами и транзакциями
 * OpenAPI spec version: 1.0.0
 */
export interface Balance {
  /** @minimum 0 */
  points: number;
  /** @minimum 0 */
  g2a: number;
}

/**
 * @nullable
 */
export type AddPointsRequestMetadata = { [key: string]: unknown } | null;

export interface AddPointsRequest {
  /**
   * @minimum 1
   * @maximum 100
   */
  amount: number;
  reason: string;
  /** @nullable */
  metadata?: AddPointsRequestMetadata;
}

/**
 * @nullable
 */
export type SubtractPointsRequestMetadata = { [key: string]: unknown } | null;

export interface SubtractPointsRequest {
  /** @minimum 1 */
  amount: number;
  reason: string;
  /** @nullable */
  metadata?: SubtractPointsRequestMetadata;
}

export type TransactionType = typeof TransactionType[keyof typeof TransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionType = {
  points_add: 'points_add',
  points_subtract: 'points_subtract',
  g2a_add: 'g2a_add',
  g2a_subtract: 'g2a_subtract',
} as const;

/**
 * @nullable
 */
export type TransactionMetadata = { [key: string]: unknown } | null;

export interface Transaction {
  id: string;
  userId: string;
  type: TransactionType;
  amount: number;
  reason: string;
  /** @nullable */
  metadata?: TransactionMetadata;
  createdAt: string;
}

export interface TransactionsResponse {
  items: Transaction[];
  /** @nullable */
  nextCursor?: string | null;
  hasMore: boolean;
}

export type ErrorResponseError = {
  code: string;
  message: string;
  /** @nullable */
  traceId?: string | null;
};

export interface ErrorResponse {
  error: ErrorResponseError;
}

/**
 * Неверный запрос
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Требуется авторизация
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Доступ запрещён
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Ресурс не найден
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Конфликт
 */
export type ConflictResponse = ErrorResponse;

/**
 * Превышен лимит запросов
 */
export type TooManyRequestsResponse = ErrorResponse;

/**
 * Внутренняя ошибка сервера
 */
export type InternalServerErrorResponse = ErrorResponse;

/**
 * Количество элементов на странице
 */
export type LimitParameter = number;

/**
 * Курсор для пагинации
 */
export type CursorParameter = string;

export type GetTransactionsParams = {
/**
 * Количество элементов на странице
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
/**
 * Курсор для пагинации
 */
cursor?: CursorParameter;
};

