/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Go2Asia Token API
 * API для работы с токенами, балансами и транзакциями
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddPointsRequest,
  BadRequestResponse,
  Balance,
  ConflictResponse,
  InternalServerErrorResponse,
  SubtractPointsRequest,
  Transaction,
  UnauthorizedResponse
} from '../token.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает текущий баланс Points и G2A токенов
 * @summary Получить баланс пользователя
 */
export const getBalance = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Balance>(
      {url: `/balance`, method: 'GET', signal
    },
      options);
    }
  



export const getGetBalanceQueryKey = () => {
    return [
    `/balance`
    ] as const;
    }

    
export const getGetBalanceQueryOptions = <TData = Awaited<ReturnType<typeof getBalance>>, TError = UnauthorizedResponse | InternalServerErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBalance>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBalanceQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBalance>>> = ({ signal }) => getBalance(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBalance>>, TError, TData> & { queryKey: QueryKey }
}

export type GetBalanceQueryResult = NonNullable<Awaited<ReturnType<typeof getBalance>>>
export type GetBalanceQueryError = UnauthorizedResponse | InternalServerErrorResponse


/**
 * @summary Получить баланс пользователя
 */

export function useGetBalance<TData = Awaited<ReturnType<typeof getBalance>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBalance>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetBalanceQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Добавляет поинты к балансу пользователя
 * @summary Добавить поинты
 */
export const addPoints = (
    addPointsRequest: AddPointsRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Transaction>(
      {url: `/balance/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addPointsRequest, signal
    },
      options);
    }
  


export const getAddPointsMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addPoints>>, TError,{data: AddPointsRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addPoints>>, TError,{data: AddPointsRequest}, TContext> => {

const mutationKey = ['addPoints'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addPoints>>, {data: AddPointsRequest}> = (props) => {
          const {data} = props ?? {};

          return  addPoints(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddPointsMutationResult = NonNullable<Awaited<ReturnType<typeof addPoints>>>
    export type AddPointsMutationBody = AddPointsRequest
    export type AddPointsMutationError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse

    /**
 * @summary Добавить поинты
 */
export const useAddPoints = <TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addPoints>>, TError,{data: AddPointsRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof addPoints>>,
        TError,
        {data: AddPointsRequest},
        TContext
      > => {

      const mutationOptions = getAddPointsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Списывает поинты с баланса пользователя
 * @summary Списать поинты
 */
export const subtractPoints = (
    subtractPointsRequest: SubtractPointsRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Transaction>(
      {url: `/balance/subtract`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: subtractPointsRequest, signal
    },
      options);
    }
  


export const getSubtractPointsMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | ConflictResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subtractPoints>>, TError,{data: SubtractPointsRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof subtractPoints>>, TError,{data: SubtractPointsRequest}, TContext> => {

const mutationKey = ['subtractPoints'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subtractPoints>>, {data: SubtractPointsRequest}> = (props) => {
          const {data} = props ?? {};

          return  subtractPoints(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SubtractPointsMutationResult = NonNullable<Awaited<ReturnType<typeof subtractPoints>>>
    export type SubtractPointsMutationBody = SubtractPointsRequest
    export type SubtractPointsMutationError = BadRequestResponse | UnauthorizedResponse | ConflictResponse | InternalServerErrorResponse

    /**
 * @summary Списать поинты
 */
export const useSubtractPoints = <TError = BadRequestResponse | UnauthorizedResponse | ConflictResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subtractPoints>>, TError,{data: SubtractPointsRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof subtractPoints>>,
        TError,
        {data: SubtractPointsRequest},
        TContext
      > => {

      const mutationOptions = getSubtractPointsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    