import type { Metadata } from 'next';
import { ModuleHero } from '@/components/modules';
import { CalendarView } from '@/components/pulse';
import { Globe } from 'lucide-react';
import { Event } from '@/components/pulse/types';

export const metadata: Metadata = {
  title: 'Pulse Asia - События и мероприятия | Go2Asia',
  description: 'Актуальные события и мероприятия в Юго-Восточной Азии',
};

// Mock данные событий в формате Event
// События распределены по ноябрю 2025 для демонстрации всех видов календаря
const mockEvents: Event[] = [
  // Текущая неделя (23-29 ноября)
  {
    id: '1',
    title: 'Утренняя йога на пляже',
    description: 'Йога-сессия на рассвете с видом на море. Подходит для всех уровней подготовки.',
    startDate: new Date('2025-11-23T06:00:00'),
    endDate: new Date('2025-11-23T07:30:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Пляж Ката',
      address: 'Пляж Ката, Пхукет',
      city: 'Пхукет',
      country: 'Таиланд',
    },
    attendeesCount: 12,
    category: 'Спорт',
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '2',
    title: 'Встреча Digital Nomads',
    description: 'Еженедельная встреча удалённых работников. Обмен опытом, нетворкинг, кофе.',
    startDate: new Date('2025-11-23T19:00:00'),
    endDate: new Date('2025-11-23T21:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Кофейня "Кофе и Код"',
      address: 'Sukhumvit Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 28,
    category: 'IT',
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    russianFriendly: true,
  },
  {
    id: '3',
    title: 'Фестиваль уличной еды',
    description: 'Гастрономический фестиваль с участием лучших уличных поваров Бангкока.',
    startDate: new Date('2025-11-24T17:00:00'),
    endDate: new Date('2025-11-24T23:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Чайна-таун',
      address: 'Yaowarat Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 150,
    category: 'Еда',
    badges: ['verified', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  {
    id: '4',
    title: 'Концерт джаз-бэнда',
    description: 'Живая музыка в атмосферном джаз-клубе. Выступление местных музыкантов.',
    startDate: new Date('2025-11-24T20:00:00'),
    endDate: new Date('2025-11-25T00:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Jazz Club Bangkok',
      address: 'Sukhumvit Soi 11, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 45,
    category: 'Музыка',
    badges: ['verified'],
    price: { type: 'paid', amount: 300, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '5',
    title: 'Мастер-класс по тайской кухне',
    description: 'Учимся готовить пад тай, том ям и другие классические блюда тайской кухни.',
    startDate: new Date('2025-11-25T10:00:00'),
    endDate: new Date('2025-11-25T13:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Cooking School Bangkok',
      address: 'Silom Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 8,
    category: 'Еда',
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 1200, currency: 'THB' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  {
    id: '6',
    title: 'Ночной рынок в Чиангмае',
    description: 'Еженедельный ночной рынок с местными ремеслами, едой и развлечениями.',
    startDate: new Date('2025-11-25T18:00:00'),
    endDate: new Date('2025-11-25T23:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Sunday Walking Street',
      address: 'Ratchadamnoen Road, Чиангмай',
      city: 'Чиангмай',
      country: 'Таиланд',
    },
    attendeesCount: 200,
    category: 'Культура',
    badges: ['free', 'repeating'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
  },
  {
    id: '7',
    title: 'Семейный пикник в парке',
    description: 'Пикник для семей с детьми. Игры, конкурсы, угощения.',
    startDate: new Date('2025-11-26T11:00:00'),
    endDate: new Date('2025-11-26T15:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Лумпини парк',
      address: 'Лумпини парк, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 35,
    category: 'Семья',
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    russianFriendly: true,
  },
  {
    id: '8',
    title: 'Технический митап: React и Next.js',
    description: 'Доклады о современных подходах к разработке на React и Next.js.',
    startDate: new Date('2025-11-26T19:30:00'),
    endDate: new Date('2025-11-26T22:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'WeWork Thonglor',
      address: 'Thonglor Soi 10, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 42,
    category: 'IT',
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'en',
    scale: 'city',
    status: 'published',
    verified: true,
  },
  {
    id: '9',
    title: 'Экскурсия по храмам',
    description: 'Пешеходная экскурсия по главным храмам Бангкока с русскоязычным гидом.',
    startDate: new Date('2025-11-27T09:00:00'),
    endDate: new Date('2025-11-27T13:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Храм Изумрудного Будды',
      address: 'Grand Palace, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 15,
    category: 'Культура',
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 800, currency: 'THB' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  {
    id: '10',
    title: 'Вечеринка на крыше',
    description: 'Закат на крыше с коктейлями и живой музыкой. Dress code: casual.',
    startDate: new Date('2025-11-27T18:00:00'),
    endDate: new Date('2025-11-28T01:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Sky Bar',
      address: 'Lebua Hotel, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 60,
    category: 'Ночная жизнь',
    badges: ['verified'],
    price: { type: 'paid', amount: 500, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '11',
    title: 'Серфинг на Бали',
    description: 'Групповой урок серфинга для начинающих. Все необходимое оборудование включено.',
    startDate: new Date('2025-11-28T08:00:00'),
    endDate: new Date('2025-11-28T11:00:00'),
    timezone: 'Asia/Jakarta',
    location: {
      name: 'Пляж Кута',
      address: 'Пляж Кута, Бали',
      city: 'Кута',
      country: 'Индонезия',
    },
    attendeesCount: 6,
    category: 'Спорт',
    badges: ['verified'],
    price: { type: 'paid', amount: 250000, currency: 'IDR' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '12',
    title: 'Фестиваль фонарей',
    description: 'Традиционный фестиваль фонарей в Чиангмае. Тысячи фонарей в небе.',
    startDate: new Date('2025-11-28T19:00:00'),
    endDate: new Date('2025-11-28T23:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Центр Чиангмая',
      address: 'Центральная площадь, Чиангмай',
      city: 'Чиангмай',
      country: 'Таиланд',
    },
    attendeesCount: 500,
    category: 'Культура',
    badges: ['verified', 'free'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
    verified: true,
  },
  {
    id: '13',
    title: 'Бранч в русском ресторане',
    description: 'Воскресный бранч с блинчиками, икрой и традиционными русскими блюдами.',
    startDate: new Date('2025-11-29T11:00:00'),
    endDate: new Date('2025-11-29T15:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Русский дом',
      address: 'Sukhumvit Soi 24, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 25,
    category: 'Еда',
    badges: ['russian-friendly', 'verified'],
    price: { type: 'paid', amount: 600, currency: 'THB' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  {
    id: '14',
    title: 'Концерт традиционной музыки',
    description: 'Выступление местных музыкантов с традиционными инструментами Вьетнама.',
    startDate: new Date('2025-11-29T20:00:00'),
    endDate: new Date('2025-11-29T22:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    location: {
      name: 'Ханойская опера',
      address: '1 Trang Tien, Ханой',
      city: 'Ханой',
      country: 'Вьетнам',
    },
    attendeesCount: 80,
    category: 'Культура',
    badges: ['verified'],
    price: { type: 'paid', amount: 200000, currency: 'VND' },
    language: 'local',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  // События на другие дни ноября
  {
    id: '15',
    title: 'Мастер-класс по медитации',
    description: 'Групповая медитация в храме. Подходит для начинающих.',
    startDate: new Date('2025-11-30T07:00:00'),
    endDate: new Date('2025-11-30T08:30:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Храм Ват Пхо',
      address: 'Sanam Chai Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 20,
    category: 'Культура',
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '16',
    title: 'Фуд-тур по Сингапуру',
    description: 'Гастрономический тур по лучшим уличным закусочным Сингапура.',
    startDate: new Date('2025-11-30T17:00:00'),
    endDate: new Date('2025-11-30T21:00:00'),
    timezone: 'Asia/Singapore',
    location: {
      name: 'Чайна-таун',
      address: 'Chinatown, Сингапур',
      city: 'Сингапур',
      country: 'Сингапур',
    },
    attendeesCount: 12,
    category: 'Еда',
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 80, currency: 'SGD' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  // События на начало декабря для демонстрации
  {
    id: '17',
    title: 'Новогодняя подготовка',
    description: 'Мастер-класс по украшению дома к Новому году в тайском стиле.',
    startDate: new Date('2025-12-01T14:00:00'),
    endDate: new Date('2025-12-01T17:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Community Center',
      address: 'Sukhumvit Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 18,
    category: 'Семья',
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    russianFriendly: true,
  },
  {
    id: '18',
    title: 'Конференция стартапов',
    description: 'Однодневная конференция для стартапов и инвесторов в ЮВА.',
    startDate: new Date('2025-12-02T09:00:00'),
    endDate: new Date('2025-12-02T18:00:00'),
    timezone: 'Asia/Singapore',
    location: {
      name: 'Marina Bay Sands',
      address: 'Marina Bay, Сингапур',
      city: 'Сингапур',
      country: 'Сингапур',
    },
    attendeesCount: 300,
    category: 'IT',
    badges: ['verified'],
    price: { type: 'paid', amount: 150, currency: 'SGD' },
    language: 'en',
    scale: 'city',
    status: 'published',
    verified: true,
  },
];

export default function PulsePage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <ModuleHero
        icon={Globe}
        title="Pulse Asia"
        description="События и мероприятия в Юго-Восточной Азии"
        gradientFrom="from-sky-500"
        gradientTo="to-sky-600"
      />

      <CalendarView
        events={mockEvents}
        initialView="month"
      />
    </div>
  );
}
