import type { Metadata } from 'next';
import { ModuleHero } from '@/components/modules';
import { PulseClient } from './PulseClient';
import { Globe } from 'lucide-react';
import { Event } from '@/components/pulse/types';

export const metadata: Metadata = {
  title: 'Pulse Asia - События и мероприятия | Go2Asia',
  description: 'Актуальные события и мероприятия в Юго-Восточной Азии',
};

// Mock данные событий в формате Event
// События равномерно распределены по ноябрю 2025 для демонстрации всех видов календаря
const mockEvents: Event[] = [
  // Начало ноября (1-10)
  {
    id: '101',
    title: 'Фестиваль воздушных змеев',
    description: 'Традиционный фестиваль запуска воздушных змеев на пляже.',
    startDate: new Date('2025-11-01T15:00:00'),
    endDate: new Date('2025-11-01T18:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Пляж Чавенг',
      address: 'Чавенг, Самуи',
      city: 'Самуи',
      country: 'Таиланд',
    },
    attendeesCount: 80,
    category: 'Культура',
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
    verified: true,
  },
  {
    id: '102',
    title: 'Урок дайвинга для начинающих',
    description: 'Первое погружение с аквалангом под руководством инструктора.',
    startDate: new Date('2025-11-02T09:00:00'),
    endDate: new Date('2025-11-02T12:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Дайв-центр',
      address: 'Патонг, Пхукет',
      city: 'Пхукет',
      country: 'Таиланд',
    },
    attendeesCount: 4,
    maxAttendees: 6,
    category: 'Спорт',
    badges: ['verified'],
    price: { type: 'paid', amount: 3500, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '103',
    title: 'Концерт живой музыки',
    description: 'Выступление местной рок-группы в баре на набережной.',
    startDate: new Date('2025-11-02T20:00:00'),
    endDate: new Date('2025-11-02T23:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    location: {
      name: 'Rock Bar Saigon',
      address: 'Район 1, Хошимин',
      city: 'Хошимин',
      country: 'Вьетнам',
    },
    attendeesCount: 50,
    category: 'Музыка',
    badges: ['verified'],
    price: { type: 'paid', amount: 150000, currency: 'VND' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '104',
    title: 'Завтрак с предпринимателями',
    description: 'Networking-завтрак для основателей стартапов и инвесторов.',
    startDate: new Date('2025-11-04T08:00:00'),
    endDate: new Date('2025-11-04T10:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Hub Bangkok',
      address: 'Sukhumvit Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 15,
    maxAttendees: 20,
    category: 'IT',
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'en',
    scale: 'city',
    status: 'published',
    verified: true,
  },
  {
    id: '105',
    title: 'Кулинарный мастер-класс: Вьетнамская кухня',
    description: 'Учимся готовить фо, бань ми и спринг-роллы.',
    startDate: new Date('2025-11-05T14:00:00'),
    endDate: new Date('2025-11-05T17:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    location: {
      name: 'Vietnam Cooking Class',
      address: 'Старый квартал, Ханой',
      city: 'Ханой',
      country: 'Вьетнам',
    },
    attendeesCount: 10,
    maxAttendees: 15,
    category: 'Еда',
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 800000, currency: 'VND' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  {
    id: '106',
    title: 'Детский праздник в парке',
    description: 'Игры, конкурсы и развлечения для детей всех возрастов.',
    startDate: new Date('2025-11-07T10:00:00'),
    endDate: new Date('2025-11-07T14:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Парк Benjakitti',
      address: 'Сукхумвит, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 40,
    category: 'Семья',
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    russianFriendly: true,
  },
  {
    id: '107',
    title: 'Вечеринка на крыше: Sunset Party',
    description: 'Встреча заката с коктейлями и диджей-сетом.',
    startDate: new Date('2025-11-08T18:00:00'),
    endDate: new Date('2025-11-08T22:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Octave Rooftop',
      address: 'Silom, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 120,
    category: 'Ночная жизнь',
    badges: ['verified'],
    price: { type: 'paid', amount: 400, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '108',
    title: 'Экскурсия по рисовым террасам',
    description: 'Пешеходная экскурсия по живописным рисовым террасам Бали.',
    startDate: new Date('2025-11-09T08:00:00'),
    endDate: new Date('2025-11-09T14:00:00'),
    timezone: 'Asia/Jakarta',
    location: {
      name: 'Tegallalang Rice Terraces',
      address: 'Убуд, Бали',
      city: 'Убуд',
      country: 'Индонезия',
    },
    attendeesCount: 12,
    category: 'Культура',
    badges: ['verified'],
    price: { type: 'paid', amount: 400000, currency: 'IDR' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '109',
    title: 'Воскресный бранч с джазом',
    description: 'Бранч-меню и живая джазовая музыка в саду.',
    startDate: new Date('2025-11-10T11:00:00'),
    endDate: new Date('2025-11-10T15:00:00'),
    timezone: 'Asia/Singapore',
    location: {
      name: 'Jazz Garden',
      address: 'Орчард, Сингапур',
      city: 'Сингапур',
      country: 'Сингапур',
    },
    attendeesCount: 35,
    category: 'Еда',
    badges: ['verified'],
    price: { type: 'paid', amount: 60, currency: 'SGD' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  
  // Середина ноября (11-20)
  {
    id: '110',
    title: 'Утренняя пробежка в парке',
    description: 'Групповая пробежка на 5 км с разминкой и растяжкой.',
    startDate: new Date('2025-11-11T06:30:00'),
    endDate: new Date('2025-11-11T07:30:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Парк Чатучак',
      address: 'Чатучак, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 25,
    category: 'Спорт',
    badges: ['free'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'place',
    status: 'published',
  },
  {
    id: '111',
    title: 'Workshop: Фотография путешествий',
    description: 'Мастер-класс по мобильной фотографии для путешественников.',
    startDate: new Date('2025-11-12T15:00:00'),
    endDate: new Date('2025-11-12T18:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Creative Space',
      address: 'Ari, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 8,
    maxAttendees: 12,
    category: 'Образование',
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 800, currency: 'THB' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  {
    id: '112',
    title: 'Традиционный танец: мастер-класс',
    description: 'Изучаем традиционные тайские танцы с профессиональными танцорами.',
    startDate: new Date('2025-11-13T17:00:00'),
    endDate: new Date('2025-11-13T19:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Культурный центр',
      address: 'Старый город, Чиангмай',
      city: 'Чиангмай',
      country: 'Таиланд',
    },
    attendeesCount: 15,
    category: 'Культура',
    badges: ['verified'],
    price: { type: 'paid', amount: 500, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '113',
    title: 'Hackathon: AI & ML',
    description: '24-часовой хакатон по искусственному интеллекту и машинному обучению.',
    startDate: new Date('2025-11-14T09:00:00'),
    endDate: new Date('2025-11-15T09:00:00'),
    timezone: 'Asia/Singapore',
    location: {
      name: 'Tech Hub Singapore',
      address: 'Раффлз Плейс, Сингапур',
      city: 'Сингапур',
      country: 'Сингапур',
    },
    attendeesCount: 80,
    maxAttendees: 100,
    category: 'IT',
    badges: ['verified'],
    price: { type: 'paid', amount: 50, currency: 'SGD' },
    language: 'en',
    scale: 'city',
    status: 'published',
    verified: true,
  },
  {
    id: '114',
    title: 'Фермерский рынок',
    description: 'Органические продукты от местных фермеров, крафтовая еда и напитки.',
    startDate: new Date('2025-11-15T08:00:00'),
    endDate: new Date('2025-11-15T13:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Lumpini Park',
      address: 'Lumpini, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 200,
    category: 'Еда',
    badges: ['free', 'repeating'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
  },
  {
    id: '115',
    title: 'Семейный пикник: Праздник осени',
    description: 'Пикник для семей с детьми с играми и конкурсами.',
    startDate: new Date('2025-11-16T10:00:00'),
    endDate: new Date('2025-11-16T15:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    location: {
      name: 'Tao Dan Park',
      address: 'Район 1, Хошимин',
      city: 'Хошимин',
      country: 'Вьетнам',
    },
    attendeesCount: 60,
    category: 'Семья',
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    russianFriendly: true,
  },
  {
    id: '116',
    title: 'Кинопоказ под звёздами',
    description: 'Показ классических фильмов на открытом воздухе.',
    startDate: new Date('2025-11-17T19:30:00'),
    endDate: new Date('2025-11-17T22:30:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Rooftop Cinema',
      address: 'Thonglor, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 40,
    maxAttendees: 50,
    category: 'Культура',
    badges: ['verified'],
    price: { type: 'paid', amount: 250, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '117',
    title: 'Медитация и звуковая терапия',
    description: 'Сессия медитации с поющими чашами.',
    startDate: new Date('2025-11-18T18:00:00'),
    endDate: new Date('2025-11-18T19:30:00'),
    timezone: 'Asia/Jakarta',
    location: {
      name: 'Yoga Barn',
      address: 'Убуд, Бали',
      city: 'Убуд',
      country: 'Индонезия',
    },
    attendeesCount: 20,
    category: 'Культура',
    badges: ['verified'],
    price: { type: 'paid', amount: 150000, currency: 'IDR' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '118',
    title: 'Электронная музыка: DJ Night',
    description: 'Выступление известного диджея из Европы.',
    startDate: new Date('2025-11-19T22:00:00'),
    endDate: new Date('2025-11-20T03:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Beam Club',
      address: 'Ekkamai, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 250,
    category: 'Ночная жизнь',
    badges: ['verified'],
    price: { type: 'paid', amount: 600, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '119',
    title: 'Велопрогулка по городу',
    description: 'Организованная велопрогулка по историческим местам Бангкока.',
    startDate: new Date('2025-11-20T07:00:00'),
    endDate: new Date('2025-11-20T10:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Старый город',
      address: 'Раттанакосин, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 18,
    maxAttendees: 25,
    category: 'Спорт',
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
  },
  
  // Текущая неделя (21-30 ноября)
  {
    id: '120',
    title: 'Джазовый вечер в кафе',
    description: 'Живая джазовая музыка в уютном кафе с видом на реку.',
    startDate: new Date('2025-11-21T20:00:00'),
    endDate: new Date('2025-11-21T23:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    location: {
      name: 'Jazz Cafe Saigon',
      address: 'Набережная, Хошимин',
      city: 'Хошимин',
      country: 'Вьетнам',
    },
    attendeesCount: 30,
    category: 'Музыка',
    badges: ['verified'],
    price: { type: 'paid', amount: 100000, currency: 'VND' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '121',
    title: 'Фестиваль кофе',
    description: 'Дегустация лучших сортов кофе из Вьетнама и мастер-классы бариста.',
    startDate: new Date('2025-11-22T10:00:00'),
    endDate: new Date('2025-11-22T18:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    location: {
      name: 'Центральная площадь',
      address: 'Ханой',
      city: 'Ханой',
      country: 'Вьетнам',
    },
    attendeesCount: 300,
    category: 'Еда',
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
    verified: true,
  },
  
  // Текущая неделя (23-29 ноября)
  {
    id: '1',
    title: 'Утренняя йога на пляже',
    description: 'Йога-сессия на рассвете с видом на море. Подходит для всех уровней подготовки.',
    startDate: new Date('2025-11-23T06:00:00'),
    endDate: new Date('2025-11-23T07:30:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Пляж Ката',
      address: 'Пляж Ката, Пхукет',
      city: 'Пхукет',
      country: 'Таиланд',
    },
    attendeesCount: 12,
    category: 'Спорт',
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '2',
    title: 'Встреча Digital Nomads',
    description: 'Еженедельная встреча удалённых работников. Обмен опытом, нетворкинг, кофе.',
    startDate: new Date('2025-11-23T19:00:00'),
    endDate: new Date('2025-11-23T21:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Кофейня "Кофе и Код"',
      address: 'Sukhumvit Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 28,
    category: 'IT',
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    russianFriendly: true,
  },
  {
    id: '3',
    title: 'Фестиваль уличной еды',
    description: 'Гастрономический фестиваль с участием лучших уличных поваров Бангкока.',
    startDate: new Date('2025-11-24T17:00:00'),
    endDate: new Date('2025-11-24T23:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Чайна-таун',
      address: 'Yaowarat Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 150,
    category: 'Еда',
    badges: ['verified', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  {
    id: '4',
    title: 'Концерт джаз-бэнда',
    description: 'Живая музыка в атмосферном джаз-клубе. Выступление местных музыкантов.',
    startDate: new Date('2025-11-24T20:00:00'),
    endDate: new Date('2025-11-25T00:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Jazz Club Bangkok',
      address: 'Sukhumvit Soi 11, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 45,
    category: 'Музыка',
    badges: ['verified'],
    price: { type: 'paid', amount: 300, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '5',
    title: 'Мастер-класс по тайской кухне',
    description: 'Учимся готовить пад тай, том ям и другие классические блюда тайской кухни.',
    startDate: new Date('2025-11-25T10:00:00'),
    endDate: new Date('2025-11-25T13:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Cooking School Bangkok',
      address: 'Silom Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 8,
    category: 'Еда',
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 1200, currency: 'THB' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  {
    id: '6',
    title: 'Ночной рынок в Чиангмае',
    description: 'Еженедельный ночной рынок с местными ремеслами, едой и развлечениями.',
    startDate: new Date('2025-11-25T18:00:00'),
    endDate: new Date('2025-11-25T23:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Sunday Walking Street',
      address: 'Ratchadamnoen Road, Чиангмай',
      city: 'Чиангмай',
      country: 'Таиланд',
    },
    attendeesCount: 200,
    category: 'Культура',
    badges: ['free', 'repeating'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
  },
  {
    id: '7',
    title: 'Семейный пикник в парке',
    description: 'Пикник для семей с детьми. Игры, конкурсы, угощения.',
    startDate: new Date('2025-11-26T11:00:00'),
    endDate: new Date('2025-11-26T15:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Лумпини парк',
      address: 'Лумпини парк, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 35,
    category: 'Семья',
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    russianFriendly: true,
  },
  {
    id: '8',
    title: 'Технический митап: React и Next.js',
    description: 'Доклады о современных подходах к разработке на React и Next.js.',
    startDate: new Date('2025-11-26T19:30:00'),
    endDate: new Date('2025-11-26T22:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'WeWork Thonglor',
      address: 'Thonglor Soi 10, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 42,
    category: 'IT',
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'en',
    scale: 'city',
    status: 'published',
    verified: true,
  },
  {
    id: '9',
    title: 'Экскурсия по храмам',
    description: 'Пешеходная экскурсия по главным храмам Бангкока с русскоязычным гидом.',
    startDate: new Date('2025-11-27T09:00:00'),
    endDate: new Date('2025-11-27T13:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Храм Изумрудного Будды',
      address: 'Grand Palace, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 15,
    category: 'Культура',
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 800, currency: 'THB' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  {
    id: '10',
    title: 'Вечеринка на крыше',
    description: 'Закат на крыше с коктейлями и живой музыкой. Dress code: casual.',
    startDate: new Date('2025-11-27T18:00:00'),
    endDate: new Date('2025-11-28T01:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Sky Bar',
      address: 'Lebua Hotel, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 60,
    category: 'Ночная жизнь',
    badges: ['verified'],
    price: { type: 'paid', amount: 500, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '11',
    title: 'Серфинг на Бали',
    description: 'Групповой урок серфинга для начинающих. Все необходимое оборудование включено.',
    startDate: new Date('2025-11-28T08:00:00'),
    endDate: new Date('2025-11-28T11:00:00'),
    timezone: 'Asia/Jakarta',
    location: {
      name: 'Пляж Кута',
      address: 'Пляж Кута, Бали',
      city: 'Кута',
      country: 'Индонезия',
    },
    attendeesCount: 6,
    category: 'Спорт',
    badges: ['verified'],
    price: { type: 'paid', amount: 250000, currency: 'IDR' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '12',
    title: 'Фестиваль фонарей',
    description: 'Традиционный фестиваль фонарей в Чиангмае. Тысячи фонарей в небе.',
    startDate: new Date('2025-11-28T19:00:00'),
    endDate: new Date('2025-11-28T23:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Центр Чиангмая',
      address: 'Центральная площадь, Чиангмай',
      city: 'Чиангмай',
      country: 'Таиланд',
    },
    attendeesCount: 500,
    category: 'Культура',
    badges: ['verified', 'free'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
    verified: true,
  },
  {
    id: '13',
    title: 'Бранч в русском ресторане',
    description: 'Воскресный бранч с блинчиками, икрой и традиционными русскими блюдами.',
    startDate: new Date('2025-11-29T11:00:00'),
    endDate: new Date('2025-11-29T15:00:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Русский дом',
      address: 'Sukhumvit Soi 24, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 25,
    category: 'Еда',
    badges: ['russian-friendly', 'verified'],
    price: { type: 'paid', amount: 600, currency: 'THB' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
  {
    id: '14',
    title: 'Концерт традиционной музыки',
    description: 'Выступление местных музыкантов с традиционными инструментами Вьетнама.',
    startDate: new Date('2025-11-29T20:00:00'),
    endDate: new Date('2025-11-29T22:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    location: {
      name: 'Ханойская опера',
      address: '1 Trang Tien, Ханой',
      city: 'Ханой',
      country: 'Вьетнам',
    },
    attendeesCount: 80,
    category: 'Культура',
    badges: ['verified'],
    price: { type: 'paid', amount: 200000, currency: 'VND' },
    language: 'local',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  // События на другие дни ноября
  {
    id: '15',
    title: 'Мастер-класс по медитации',
    description: 'Групповая медитация в храме. Подходит для начинающих.',
    startDate: new Date('2025-11-30T07:00:00'),
    endDate: new Date('2025-11-30T08:30:00'),
    timezone: 'Asia/Bangkok',
    location: {
      name: 'Храм Ват Пхо',
      address: 'Sanam Chai Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
    },
    attendeesCount: 20,
    category: 'Культура',
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
  },
  {
    id: '16',
    title: 'Фуд-тур по Сингапуру',
    description: 'Гастрономический тур по лучшим уличным закусочным Сингапура.',
    startDate: new Date('2025-11-30T17:00:00'),
    endDate: new Date('2025-11-30T21:00:00'),
    timezone: 'Asia/Singapore',
    location: {
      name: 'Чайна-таун',
      address: 'Chinatown, Сингапур',
      city: 'Сингапур',
      country: 'Сингапур',
    },
    attendeesCount: 12,
    category: 'Еда',
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 80, currency: 'SGD' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
  },
];

export default function PulsePage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <ModuleHero
        icon={Globe}
        title="Pulse Asia"
        description="События и мероприятия в Юго-Восточной Азии"
        gradientFrom="from-sky-500"
        gradientTo="to-sky-600"
      />

      <PulseClient events={mockEvents} />
    </div>
  );
}
