/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Go2Asia Content API
 * API для работы с контентом (Atlas, Pulse, Blog)
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Article,
  ArticlesResponse,
  BadRequestResponse,
  GetArticlesParams,
  InternalServerErrorResponse,
  NotFoundResponse
} from '../content.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает список статей блога
 * @summary Получить список статей
 */
export const getArticles = (
    params?: GetArticlesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ArticlesResponse>(
      {url: `/articles`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetArticlesQueryKey = (params?: GetArticlesParams,) => {
    return [
    `/articles`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetArticlesQueryOptions = <TData = Awaited<ReturnType<typeof getArticles>>, TError = BadRequestResponse | InternalServerErrorResponse>(params?: GetArticlesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getArticles>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArticlesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getArticles>>> = ({ signal }) => getArticles(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getArticles>>, TError, TData> & { queryKey: QueryKey }
}

export type GetArticlesQueryResult = NonNullable<Awaited<ReturnType<typeof getArticles>>>
export type GetArticlesQueryError = BadRequestResponse | InternalServerErrorResponse


/**
 * @summary Получить список статей
 */

export function useGetArticles<TData = Awaited<ReturnType<typeof getArticles>>, TError = BadRequestResponse | InternalServerErrorResponse>(
 params?: GetArticlesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getArticles>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetArticlesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получить статью по slug
 */
export const getArticleBySlug = (
    slug: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Article>(
      {url: `/articles/${slug}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetArticleBySlugQueryKey = (slug?: string,) => {
    return [
    `/articles/${slug}`
    ] as const;
    }

    
export const getGetArticleBySlugQueryOptions = <TData = Awaited<ReturnType<typeof getArticleBySlug>>, TError = NotFoundResponse | InternalServerErrorResponse>(slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getArticleBySlug>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArticleBySlugQueryKey(slug);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getArticleBySlug>>> = ({ signal }) => getArticleBySlug(slug, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getArticleBySlug>>, TError, TData> & { queryKey: QueryKey }
}

export type GetArticleBySlugQueryResult = NonNullable<Awaited<ReturnType<typeof getArticleBySlug>>>
export type GetArticleBySlugQueryError = NotFoundResponse | InternalServerErrorResponse


/**
 * @summary Получить статью по slug
 */

export function useGetArticleBySlug<TData = Awaited<ReturnType<typeof getArticleBySlug>>, TError = NotFoundResponse | InternalServerErrorResponse>(
 slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getArticleBySlug>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetArticleBySlugQueryOptions(slug,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




