/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Go2Asia Auth API
 * API для работы с авторизацией и профилями пользователей
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  ClerkWebhook200,
  ClerkWebhookEvent,
  InternalServerErrorResponse,
  UnauthorizedResponse
} from '../auth.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Принимает события от Clerk (создание/обновление/удаление пользователей)
 * @summary Webhook от Clerk
 */
export const clerkWebhook = (
    clerkWebhookEvent: ClerkWebhookEvent,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ClerkWebhook200>(
      {url: `/webhooks/clerk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: clerkWebhookEvent, signal
    },
      options);
    }
  


export const getClerkWebhookMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clerkWebhook>>, TError,{data: ClerkWebhookEvent}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof clerkWebhook>>, TError,{data: ClerkWebhookEvent}, TContext> => {

const mutationKey = ['clerkWebhook'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clerkWebhook>>, {data: ClerkWebhookEvent}> = (props) => {
          const {data} = props ?? {};

          return  clerkWebhook(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ClerkWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof clerkWebhook>>>
    export type ClerkWebhookMutationBody = ClerkWebhookEvent
    export type ClerkWebhookMutationError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse

    /**
 * @summary Webhook от Clerk
 */
export const useClerkWebhook = <TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clerkWebhook>>, TError,{data: ClerkWebhookEvent}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof clerkWebhook>>,
        TError,
        {data: ClerkWebhookEvent},
        TContext
      > => {

      const mutationOptions = getClerkWebhookMutationOptions(options);

      return useMutation(mutationOptions);
    }
    