/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Go2Asia Referral API
 * API для работы с реферальной программой
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  ConflictResponse,
  GetReferralTreeParams,
  InternalServerErrorResponse,
  ReferralStats,
  ReferralTree,
  RegisterReferralRequest,
  RegisterReferralResponse,
  UnauthorizedResponse
} from '../referral.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает статистику реферальной программы пользователя
 * @summary Получить статистику рефералов
 */
export const getReferralStats = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ReferralStats>(
      {url: `/stats`, method: 'GET', signal
    },
      options);
    }
  



export const getGetReferralStatsQueryKey = () => {
    return [
    `/stats`
    ] as const;
    }

    
export const getGetReferralStatsQueryOptions = <TData = Awaited<ReturnType<typeof getReferralStats>>, TError = UnauthorizedResponse | InternalServerErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReferralStats>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferralStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferralStats>>> = ({ signal }) => getReferralStats(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferralStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetReferralStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getReferralStats>>>
export type GetReferralStatsQueryError = UnauthorizedResponse | InternalServerErrorResponse


/**
 * @summary Получить статистику рефералов
 */

export function useGetReferralStats<TData = Awaited<ReturnType<typeof getReferralStats>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReferralStats>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetReferralStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает иерархию рефералов пользователя
 * @summary Получить дерево рефералов
 */
export const getReferralTree = (
    params?: GetReferralTreeParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ReferralTree>(
      {url: `/tree`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetReferralTreeQueryKey = (params?: GetReferralTreeParams,) => {
    return [
    `/tree`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetReferralTreeQueryOptions = <TData = Awaited<ReturnType<typeof getReferralTree>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(params?: GetReferralTreeParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReferralTree>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferralTreeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferralTree>>> = ({ signal }) => getReferralTree(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferralTree>>, TError, TData> & { queryKey: QueryKey }
}

export type GetReferralTreeQueryResult = NonNullable<Awaited<ReturnType<typeof getReferralTree>>>
export type GetReferralTreeQueryError = UnauthorizedResponse | InternalServerErrorResponse


/**
 * @summary Получить дерево рефералов
 */

export function useGetReferralTree<TData = Awaited<ReturnType<typeof getReferralTree>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
 params?: GetReferralTreeParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReferralTree>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetReferralTreeQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Регистрирует нового пользователя по реферальной ссылке
 * @summary Зарегистрировать реферала
 */
export const registerReferral = (
    registerReferralRequest: RegisterReferralRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterReferralResponse>(
      {url: `/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerReferralRequest, signal
    },
      options);
    }
  


export const getRegisterReferralMutationOptions = <TError = BadRequestResponse | ConflictResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerReferral>>, TError,{data: RegisterReferralRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerReferral>>, TError,{data: RegisterReferralRequest}, TContext> => {

const mutationKey = ['registerReferral'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerReferral>>, {data: RegisterReferralRequest}> = (props) => {
          const {data} = props ?? {};

          return  registerReferral(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterReferralMutationResult = NonNullable<Awaited<ReturnType<typeof registerReferral>>>
    export type RegisterReferralMutationBody = RegisterReferralRequest
    export type RegisterReferralMutationError = BadRequestResponse | ConflictResponse | InternalServerErrorResponse

    /**
 * @summary Зарегистрировать реферала
 */
export const useRegisterReferral = <TError = BadRequestResponse | ConflictResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerReferral>>, TError,{data: RegisterReferralRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof registerReferral>>,
        TError,
        {data: RegisterReferralRequest},
        TContext
      > => {

      const mutationOptions = getRegisterReferralMutationOptions(options);

      return useMutation(mutationOptions);
    }
    