/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Go2Asia Token API
 * API для работы с токенами, балансами и транзакциями
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetTransactionsParams,
  InternalServerErrorResponse,
  TransactionsResponse,
  UnauthorizedResponse
} from '../token.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает историю транзакций пользователя с пагинацией
 * @summary Получить историю транзакций
 */
export const getTransactions = (
    params?: GetTransactionsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TransactionsResponse>(
      {url: `/transactions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetTransactionsQueryKey = (params?: GetTransactionsParams,) => {
    return [
    `/transactions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getTransactions>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(params?: GetTransactionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTransactionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTransactions>>> = ({ signal }) => getTransactions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getTransactions>>>
export type GetTransactionsQueryError = UnauthorizedResponse | InternalServerErrorResponse


/**
 * @summary Получить историю транзакций
 */

export function useGetTransactions<TData = Awaited<ReturnType<typeof getTransactions>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
 params?: GetTransactionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTransactionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




